name: DVC Pull Latest Data

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup latest DVC version
      uses: iterative/setup-dvc@v1

    - name: Do DVC pull on AWS storage
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        dvc pull